//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construct.Tfs.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Construct.Tfs.Activities.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Agent.
        /// </summary>
        internal static string BuildAgentCheckInComment {
            get {
                return ResourceManager.GetString("BuildAgentCheckInComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The build version was not incremented successfully..
        /// </summary>
        internal static string BuildVersionIncrementFailureError {
            get {
                return ResourceManager.GetString("BuildVersionIncrementFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending changes to Build agent workspace checked in with changeset number &apos;{0}&apos;.
        /// </summary>
        internal static string CheckInCompleted {
            get {
                return ResourceManager.GetString("CheckInCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} to {1}....
        /// </summary>
        internal static string CopyingFiles {
            get {
                return ResourceManager.GetString("CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copy destination folder is: {0}.
        /// </summary>
        internal static string CopyLocationDestinationMessage {
            get {
                return ResourceManager.GetString("CopyLocationDestinationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationLocation is empty..
        /// </summary>
        internal static string CopyLocationDestinationMissingError {
            get {
                return ResourceManager.GetString("CopyLocationDestinationMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copy filespec is: {0}.
        /// </summary>
        internal static string CopyLocationFileSpecMessage {
            get {
                return ResourceManager.GetString("CopyLocationFileSpecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copy source folder is: {0}.
        /// </summary>
        internal static string CopyLocationSourceMessage {
            get {
                return ResourceManager.GetString("CopyLocationSourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLocation is empty..
        /// </summary>
        internal static string CopyLocationSourceMissingError {
            get {
                return ResourceManager.GetString("CopyLocationSourceMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLocation &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string CopySourceLocationMissingError {
            get {
                return ResourceManager.GetString("CopySourceLocationMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating destination folder &apos;{0}&apos;..
        /// </summary>
        internal static string CreateDestinationLocation {
            get {
                return ResourceManager.GetString("CreateDestinationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaulting to inclusion of AssemblyFileVersion attribute in increment..
        /// </summary>
        internal static string DefaultIncludeAssemblyFileVersionAttribute {
            get {
                return ResourceManager.GetString("DefaultIncludeAssemblyFileVersionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaulting to inclusion of AssemblyVersion attribute in increment..
        /// </summary>
        internal static string DefaultIncludeAssemblyVersionAttribute {
            get {
                return ResourceManager.GetString("DefaultIncludeAssemblyVersionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &apos;{0}&apos;....
        /// </summary>
        internal static string DownloadingFile {
            get {
                return ResourceManager.GetString("DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemping to Filter incoming items..
        /// </summary>
        internal static string FilterItemsMessage {
            get {
                return ResourceManager.GetString("FilterItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly info file mask is empty and invalid..
        /// </summary>
        internal static string InvalidAssemblyInfoMaskError {
            get {
                return ResourceManager.GetString("InvalidAssemblyInfoMaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid BuildDetail exists..
        /// </summary>
        internal static string InvalidBuildDetailError {
            get {
                return ResourceManager.GetString("InvalidBuildDetailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string InvalidDirectoryError {
            get {
                return ResourceManager.GetString("InvalidDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verison file path &apos;{0}&apos; is invalid, it doesn&apos;t exist..
        /// </summary>
        internal static string InvalidFullVersionFilePathError {
            get {
                return ResourceManager.GetString("InvalidFullVersionFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OctetToIncrement &apos;{0}&apos; is not valid, it must be a value between 1 &amp; 4.
        /// </summary>
        internal static string InvalidOctetToIncrementError {
            get {
                return ResourceManager.GetString("InvalidOctetToIncrementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; to the StatLight executable doesn&apos;t exist..
        /// </summary>
        internal static string InvalidStatLightExeError {
            get {
                return ResourceManager.GetString("InvalidStatLightExeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; to the test binary doesn&apos;t exist..
        /// </summary>
        internal static string InvalidTestDllError {
            get {
                return ResourceManager.GetString("InvalidTestDllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TestParameters were invalid..
        /// </summary>
        internal static string InvalidTestParameters {
            get {
                return ResourceManager.GetString("InvalidTestParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test results file &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string InvalidTestResultsFileError {
            get {
                return ResourceManager.GetString("InvalidTestResultsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAP files were specified for testing..
        /// </summary>
        internal static string InvalidTestXapList {
            get {
                return ResourceManager.GetString("InvalidTestXapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find user {0} in TFS..
        /// </summary>
        internal static string InvalidTfsUserError {
            get {
                return ResourceManager.GetString("InvalidTfsUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verison file path is empty and invalid..
        /// </summary>
        internal static string InvalidVersionFilePathError {
            get {
                return ResourceManager.GetString("InvalidVersionFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of ItemsToFilter is required..
        /// </summary>
        internal static string ItemsToFilterMissingError {
            get {
                return ResourceManager.GetString("ItemsToFilterMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***NO_CI***.
        /// </summary>
        internal static string NoCICheckInComment {
            get {
                return ResourceManager.GetString("NoCICheckInComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NuGet package filespec is: {0}.
        /// </summary>
        internal static string NuGetPackagesFileSpecMessage {
            get {
                return ResourceManager.GetString("NuGetPackagesFileSpecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLocation &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string NuGetPackageSourceLocationMissingError {
            get {
                return ResourceManager.GetString("NuGetPackageSourceLocationMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NuGet package source folder is: {0}.
        /// </summary>
        internal static string NuGetPackageSourceMessage {
            get {
                return ResourceManager.GetString("NuGetPackageSourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLocation is empty..
        /// </summary>
        internal static string NuGetPackageSourceMissingError {
            get {
                return ResourceManager.GetString("NuGetPackageSourceMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination NuGet Server is: {0}.
        /// </summary>
        internal static string NuGetServerUriMessage {
            get {
                return ResourceManager.GetString("NuGetServerUriMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationNuGetUri is empty..
        /// </summary>
        internal static string NuGetServerUriMissingError {
            get {
                return ResourceManager.GetString("NuGetServerUriMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version found.
        /// </summary>
        internal static string OctetToIncrementFailedReturnValue {
            get {
                return ResourceManager.GetString("OctetToIncrementFailedReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; build-related changes undone..
        /// </summary>
        internal static string PendingChangesUndoneError {
            get {
                return ResourceManager.GetString("PendingChangesUndoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Checkin.
        /// </summary>
        internal static string PolicyOverrideCheckInComment {
            get {
                return ResourceManager.GetString("PolicyOverrideCheckInComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegexPattern is required.
        /// </summary>
        internal static string RegexPatternMissingError {
            get {
                return ResourceManager.GetString("RegexPatternMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatLight TestRun Id: {0}.
        /// </summary>
        internal static string StatlightTestRunId {
            get {
                return ResourceManager.GetString("StatlightTestRunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ttt.
        /// </summary>
        internal static string te {
            get {
                return ResourceManager.GetString("te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check-in pending changes within the Build Agent workspace. Undo-ing any pending build-related changes..
        /// </summary>
        internal static string UnableToCheckInError {
            get {
                return ResourceManager.GetString("UnableToCheckInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find current Windows user..
        /// </summary>
        internal static string UnableToFindWindowsUserError {
            get {
                return ResourceManager.GetString("UnableToFindWindowsUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results file specified, defaulting to {0}.trx..
        /// </summary>
        internal static string UsingDefaultTestResultFile {
            get {
                return ResourceManager.GetString("UsingDefaultTestResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results file specified, defaulting to MSGenericTest..
        /// </summary>
        internal static string UsingDefaultTestResultFileType {
            get {
                return ResourceManager.GetString("UsingDefaultTestResultFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; found....
        /// </summary>
        internal static string VersionFileFound {
            get {
                return ResourceManager.GetString("VersionFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incrementing the &apos;{0}&apos; attribute in the file &apos;{1}&apos; to &apos;{2}&apos;.&quot;.
        /// </summary>
        internal static string VersionIncremented {
            get {
                return ResourceManager.GetString("VersionIncremented", resourceCulture);
            }
        }
    }
}
