//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coldwater.Construct.Build.Activities.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coldwater.Construct.Build.Activities.Test.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;ClassLibrary2&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;Microsoft&quot;)]
        ///[assembly: AssemblyProduct(&quot;ClassLibrary2&quot;)]
        ///[assem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo_cs {
            get {
                return ResourceManager.GetString("AssemblyInfo_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports System
        ///Imports System.Reflection
        ///Imports System.Runtime.InteropServices
        ///
        ///&apos; General Information about an assembly is controlled through the following 
        ///&apos; set of attributes. Change these attribute values to modify the information
        ///&apos; associated with an assembly.
        ///
        ///&apos; Review the values of the assembly attributes
        ///
        ///&lt;Assembly: AssemblyTitle(&quot;ClassLibrary1&quot;)&gt; 
        ///&lt;Assembly: AssemblyDescription(&quot;&quot;)&gt; 
        ///&lt;Assembly: AssemblyCompany(&quot;Microsoft&quot;)&gt; 
        ///&lt;Assembly: AssemblyProduct(&quot;ClassLibrary1&quot;)&gt; 
        ///&lt;Assembly: Ass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo_vb {
            get {
                return ResourceManager.GetString("AssemblyInfo_vb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234.
        /// </summary>
        internal static string BuildNumber {
            get {
                return ResourceManager.GetString("BuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///VS_VERSION_INFO VERSIONINFO
        /// FILEVERSION 1,2,3,4
        /// PRODUCTVERSION 1,2,3,4
        /// FILEFLAGSMASK 0x3fL
        ///#ifdef _DEBUG
        /// FILEFLAGS 0x1L
        ///#else
        /// FILEFLAGS 0x0L
        ///#endif
        /// FILEOS 0x4L
        /// FILETYPE 0x1L
        /// FILESUBTYPE 0x0L
        ///BEGIN
        ///    BLOCK &quot;StringFileInfo&quot;
        ///    BEGIN
        ///        BLOCK &quot;040904e4&quot;
        ///        BEGIN
        ///            VALUE &quot;CompanyName&quot;, &quot;Coldwater Software&quot;
        ///            VALUE &quot;FileDescription&quot;, &quot;Construct&quot;
        ///            VALUE &quot;FileVersion&quot;, &quot;1.2.3.4&quot;
        ///            VALUE &quot;InternalName&quot;, &quot;Construct.exe&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CppVersion_rc {
            get {
                return ResourceManager.GetString("CppVersion_rc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SampleNuGetPackage {
            get {
                object obj = ResourceManager.GetObject("SampleNuGetPackage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] simple_ps1 {
            get {
                object obj = ResourceManager.GetObject("simple_ps1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// [assembly: AssemblyVersion()]
        ///[assembly: AssemblyFileVersion(&quot;2009.11.16.5&quot;)].
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
